### ISSUE TITLE
Add/change changeset comment

### ISSUE THREAD

**Issue by habi** [OpenStreetEditor/OpenStreetEditor#1]
I've uploaded [a changeset](https://www.openstreetmap.org/changeset/136165045), but found no way of adding a changeset comment.
Either an automatic changeset comment need to be generated or the user has to be able to enter a comment, since `(no comment)` is not really acceptable in my opinion.

**Comment by habi** [comment]
Both https://github.com/Zverik/every_door and https://github.com/organicmaps/organicmaps/ automatically generate changeset comments, based on changed data.

**Comment by aSeniyants** [comment]
adding a comment will be added in the next version
