### ISSUE TITLE
Changeset tags

### ISSUE THREAD

**Issue by habi** [OpenStreetEditor/OpenStreetEditor#2]
Uploaded changeset are tagged with `contact=https://t.me/OpenStreetEditor`, which - in my opinion - should be used as prefix for contact possibilities for POIS: https://wiki.openstreetmap.org/w/index.php?title=Key:contact:*

If you insist on adding this tag to every changeset, I would expand it to `contact:telegram`.

**Comment by aSeniyants** [comment]
fixed
