### ISSUE TITLE
Tag search 

### ISSUE THREAD

**Issue by habi** [OpenStreetEditor/OpenStreetEditor#3]
Adding a new node *needs* a search.
Drilling down the list to the item one wants to add can be very cumbersome.

If I want to add an `amenity=fountain`, I have to click 'Man Made' > 'Water' > 'Fountain' but am not sure if I should actually start with 'Water'.
Searching for 'fountain' at the start of the drill-down list would help tremendously.

**Comment by aSeniyants** [comment]
@habi yes, adding a search bar would make sense

**Comment by aSeniyants** [comment]
The application features a search function for presets.
